controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

# Single joint position controllers
limb1_position_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - limb1_to_base
    state_publish_rate: 50
    action_monitor_rate: 20

limb2_position_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - limb2_to_limb1
    state_publish_rate: 50
    action_monitor_rate: 20

limb3_position_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - limb3_to_limb2
    state_publish_rate: 50
    action_monitor_rate: 20
