  # # CLOCK (GZ → ROS)
  # - ros_topic_name: "/clock"
  #   gz_topic_name: "/clock"
  #   ros_type_name: "rosgraph_msgs/msg/Clock"
  #   gz_type_name: "gz.msgs.Clock"
  #   direction: GZ_TO_ROS

  # # JOINT STATES from Gazebo → ROS
  # - ros_topic_name: "/joint_states"
  #   gz_topic_name: "/world/default/model/hexapod/joint_state"
  #   ros_type_name: "sensor_msgs/msg/JointState"
  #   gz_type_name: "gz.msgs.Model"
  #   direction: GZ_TO_ROS

  # # JOINT COMMANDS from ROS → Gazebo
  # - ros_topic_name: "/joint_trajectory_controller/joint_trajectory"
  #   gz_topic_name: "/model/hexapod/joint_trajectory"
  #   ros_type_name: "trajectory_msgs/msg/JointTrajectory"
  #   gz_type_name: "gz.msgs.JointTrajectory"
  #   direction: ROS_TO_GZ
  # CLOCK


#   - ros_topic_name: "/clock"
#     gz_topic_name: "/clock"
#     ros_type_name: "rosgraph_msgs/msg/Clock"
#     gz_type_name: "gz.msgs.Clock"
#     direction: GZ_TO_ROS

#   # JOINT STATES
#   - ros_topic_name: "/joint_states"
#     gz_topic_name: "/world/default/model/hexapod/joint_state"
#     ros_type_name: "sensor_msgs/msg/JointState"
#     gz_type_name: "gz.msgs.Model"
#     direction: GZ_TO_ROS

#   # JOINT COMMANDS
#   - ros_topic_name: "/joint_trajectory_controller/joint_trajectory"
#     gz_topic_name: "/world/default/model/hexapod/joint_trajectory"
#     ros_type_name: "trajectory_msgs/msg/JointTrajectory"
#     gz_type_name: "gz.msgs.JointTrajectory"
#     direction: ROS_TO_GZ

#